language: go

go:
  - 1.9
  - master

os:
  - linux

before_install:
  - go get -v github.com/klauspost/pgzip
  - go get -v github.com/go-redis/redis
  - go get -v github.com/remeh/sizedwaitgroup

script:
  - go test -bench=Leggizip